LOCAL_C_INCLUDES := ../../../../extern/irrogles/include \
../../../../extern/irrogles/source/Irrlicht/zlib 

LOCAL_CFLAGS := -DIRRLICHT_EXPORTS \
-DANDROID 

LOCAL_SRC_FILES := ../../../../extern/irrogles/source/Irrlicht/CDefaultGUIElementFactory.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIButton.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUICheckbox.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIColorSelectDialog.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIComboBox.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIContextMenu.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIEditBox.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIEnvironment.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIFileOpenDialog.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIFont.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIImage.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIImageList.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIInOutFader.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIListBox.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIMenu.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIMeshViewer.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIMessageBox.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIModalScreen.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIScrollBar.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUISkin.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUISpinBox.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUISpriteBank.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIStaticText.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUITabControl.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUITable.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIToolBar.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUITreeView.cpp \
../../../../extern/irrogles/source/Irrlicht/CGUIWindow.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/aescrypt.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/aeskey.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/aestab.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/fileenc.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/hmac.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/prng.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/pwd2key.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/sha1.cpp \
../../../../extern/irrogles/source/Irrlicht/aesGladman/sha2.cpp \
../../../../extern/irrogles/source/Irrlicht/zlib/adler32.c \
../../../../extern/irrogles/source/Irrlicht/zlib/compress.c \
../../../../extern/irrogles/source/Irrlicht/zlib/crc32.c \
../../../../extern/irrogles/source/Irrlicht/zlib/deflate.c \
../../../../extern/irrogles/source/Irrlicht/zlib/inffast.c \
../../../../extern/irrogles/source/Irrlicht/zlib/inflate.c \
../../../../extern/irrogles/source/Irrlicht/zlib/inftrees.c \
../../../../extern/irrogles/source/Irrlicht/zlib/trees.c \
../../../../extern/irrogles/source/Irrlicht/zlib/uncompr.c \
../../../../extern/irrogles/source/Irrlicht/zlib/zutil.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jaricom.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcapimin.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcapistd.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcarith.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jccoefct.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jccolor.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcdctmgr.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jchuff.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcinit.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcmainct.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcmarker.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcmaster.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcomapi.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcparam.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcprepct.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jcsample.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jctrans.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdapimin.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdapistd.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdarith.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdatadst.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdatasrc.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdcoefct.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdcolor.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jddctmgr.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdhuff.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdinput.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdmainct.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdmarker.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdmaster.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdmerge.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdpostct.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdsample.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jdtrans.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jerror.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jfdctflt.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jfdctfst.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jfdctint.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jidctflt.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jidctfst.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jidctint.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jmemmgr.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jmemnobs.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jquant1.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jquant2.c \
../../../../extern/irrogles/source/Irrlicht/jpeglib/jutils.c \
../../../../extern/irrogles/source/Irrlicht/libpng/example.c \
../../../../extern/irrogles/source/Irrlicht/libpng/png.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngerror.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pnggccrd.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngget.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngmem.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngpread.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngread.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngrio.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngrtran.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngrutil.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngset.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngtest.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngtrans.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngvcrd.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngwio.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngwrite.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngwtran.c \
../../../../extern/irrogles/source/Irrlicht/libpng/pngwutil.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/blocksort.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/bzcompress.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/bzlib.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/crctable.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/decompress.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/huffman.c \
../../../../extern/irrogles/source/Irrlicht/bzip2/randtable.c \
../../../../extern/irrogles/source/Irrlicht/lzma/LzmaDec.c 

