LOCAL_C_INCLUDES := ../../../../extern/gameswf \
../../../../extern/gameswf \
../../../../extern/gameswf \
../../../../extern/gameswf 

LOCAL_CFLAGS := LOCAL_SRC_FILES := ../../../../extern/gameswf/base/component_hackery.cpp \
../../../../extern/gameswf/base/configvars.cpp \
../../../../extern/gameswf/base/container.cpp \
../../../../extern/gameswf/base/ear_clip_triangulate_float.cpp \
../../../../extern/gameswf/base/ear_clip_triangulate_sint16.cpp \
../../../../extern/gameswf/base/file_util.cpp \
../../../../extern/gameswf/base/image.cpp \
../../../../extern/gameswf/base/image_filters.cpp \
../../../../extern/gameswf/base/jpeg.cpp \
../../../../extern/gameswf/base/logger.cpp \
../../../../extern/gameswf/base/membuf.cpp \
../../../../extern/gameswf/base/png_helper.cpp \
../../../../extern/gameswf/base/postscript.cpp \
../../../../extern/gameswf/base/triangulate_float.cpp \
../../../../extern/gameswf/base/triangulate_sint32.cpp \
../../../../extern/gameswf/base/tu_file.cpp \
../../../../extern/gameswf/base/tu_file_SDL.cpp \
../../../../extern/gameswf/base/tu_gc_singlethreaded_marksweep.cpp \
../../../../extern/gameswf/base/tu_gc_test.cpp \
../../../../extern/gameswf/base/tu_loadlib.cpp \
../../../../extern/gameswf/base/tu_random.cpp \
../../../../extern/gameswf/base/tu_timer.cpp \
../../../../extern/gameswf/base/tu_types.cpp \
../../../../extern/gameswf/base/utf8.cpp \
../../../../extern/gameswf/base/utility.cpp \
../../../../extern/gameswf/base/zlib_adapter.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_array.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_boolean.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_broadcaster.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_class.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_color.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_color_transform.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_date.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_event.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_flash.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_geom.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_global.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_key.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_loadvars.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_math.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_matrix.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_mcloader.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_mouse.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_mouse_event.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_netconnection.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_netstream.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_number.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_point.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_selection.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_sharedobject.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_sound.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_string.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_textformat.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_transform.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_xml.cpp \
../../../../extern/gameswf/gameswf_as_classes/as_xmlsocket.cpp \
../../../../extern/gameswf/gameswf/gameswf_abc.cpp \
../../../../extern/gameswf/gameswf/gameswf_action.cpp \
../../../../extern/gameswf/gameswf/gameswf_as_sprite.cpp \
../../../../extern/gameswf/gameswf/gameswf_avm2.cpp \
../../../../extern/gameswf/gameswf/gameswf_avm2_jit.cpp \
../../../../extern/gameswf/gameswf/gameswf_button.cpp \
../../../../extern/gameswf/gameswf/gameswf_canvas.cpp \
../../../../extern/gameswf/gameswf/gameswf_character.cpp \
../../../../extern/gameswf/gameswf/gameswf_disasm.cpp \
../../../../extern/gameswf/gameswf/gameswf_dlist.cpp \
../../../../extern/gameswf/gameswf/gameswf_environment.cpp \
../../../../extern/gameswf/gameswf/gameswf_filters.cpp \
../../../../extern/gameswf/gameswf/gameswf_font.cpp \
../../../../extern/gameswf/gameswf/gameswf_fontlib.cpp \
../../../../extern/gameswf/gameswf/gameswf_freetype.cpp \
../../../../extern/gameswf/gameswf/gameswf_function.cpp \
../../../../extern/gameswf/gameswf/gameswf_impl.cpp \
../../../../extern/gameswf/gameswf/gameswf_jit.cpp \
../../../../extern/gameswf/gameswf/gameswf_jit_opcode.cpp \
../../../../extern/gameswf/gameswf/gameswf_listener.cpp \
../../../../extern/gameswf/gameswf/gameswf_log.cpp \
../../../../extern/gameswf/gameswf/gameswf_morph2.cpp \
../../../../extern/gameswf/gameswf/gameswf_movie_def.cpp \
../../../../extern/gameswf/gameswf/gameswf_mutex.cpp \
../../../../extern/gameswf/gameswf/gameswf_object.cpp \
../../../../extern/gameswf/gameswf/gameswf_parser.cpp \
../../../../extern/gameswf/gameswf/gameswf_player.cpp \
../../../../extern/gameswf/gameswf/gameswf_processor.cpp \
../../../../extern/gameswf/gameswf/gameswf_render.cpp \
../../../../extern/gameswf/gameswf/gameswf_render_handler_irrlicht.cpp \
../../../../extern/gameswf/gameswf/gameswf_render_handler_ogl.cpp \
../../../../extern/gameswf/gameswf/gameswf_render_handler_ogles.cpp \
../../../../extern/gameswf/gameswf/gameswf_root.cpp \
../../../../extern/gameswf/gameswf/gameswf_shape.cpp \
../../../../extern/gameswf/gameswf/gameswf_sound.cpp \
../../../../extern/gameswf/gameswf/gameswf_sound_handler_openal.cpp \
../../../../extern/gameswf/gameswf/gameswf_sound_handler_sdl.cpp \
../../../../extern/gameswf/gameswf/gameswf_sprite.cpp \
../../../../extern/gameswf/gameswf/gameswf_sprite_def.cpp \
../../../../extern/gameswf/gameswf/gameswf_stream.cpp \
../../../../extern/gameswf/gameswf/gameswf_styles.cpp \
../../../../extern/gameswf/gameswf/gameswf_tesselate.cpp \
../../../../extern/gameswf/gameswf/gameswf_text.cpp \
../../../../extern/gameswf/gameswf/gameswf_tools.cpp \
../../../../extern/gameswf/gameswf/gameswf_types.cpp \
../../../../extern/gameswf/gameswf/gameswf_value.cpp \
../../../../extern/gameswf/gameswf/gameswf_video_impl.cpp
